In [119]:
# manipulation des données
import numpy as np
import pandas as pd

# matplotlib et seaborn pour les représentations graphiques
import matplotlib.pyplot as plt
import seaborn as sns

In [120]:
df = pd.read_csv("../Data/2.sample_dataset.csv")
df = df.dropna(subset=['words'])

In [121]:
df_sample = df.sample(100)

In [122]:
df_sample['target'].value_counts()

target
0    54
1    46
Name: count, dtype: int64

In [123]:
import torch
from transformers import AutoModel, AutoTokenizer

In [124]:
#bertweet = AutoModel.from_pretrained("vinai/bertweet-base")
#tokenizer = AutoTokenizer.from_pretrained("vinai/bertweet-base", use_fast=False)

In [125]:
bertweet = AutoModel.from_pretrained("vinai/bertweet-base")
tokenizer = AutoTokenizer.from_pretrained("vinai/bertweet-base", use_fast=False)

tabX = []
for sentence in df_sample['words']:
    testX = tokenizer.encode(sentence, return_tensors='pt')
    tabX.append(testX)

tabY = []
for i in tabX:
    with torch.no_grad():
        outputs = bertweet(i)
    
    # Accéder à la dernière couche cachée (last_hidden_states)
    last_hidden_state = outputs[0]
    
    # Utiliser la sortie de la dernière couche cachée pour la classification
    #logits = last_hidden_state[:, 0, :]  # Utiliser le premier token CLS
    
    #tabY.append(logits)
    tabY.append(last_hidden_state)
# Concaténer les embeddings
features_tensor = torch.cat(tabY, dim=0)

# Calculer les prédictions
predictions = torch.nn.Softmax(dim=-1)(features_tensor)



emoji is not installed, thus not converting emoticons or emojis into text. Install emoji: pip3 install emoji==0.6.0


RuntimeError: Sizes of tensors must match except in dimension 0. Expected size 11 but got size 5 for tensor number 1 in the list.

In [117]:
last_hidden_state

tensor([[[ 0.1297,  0.0927, -0.0044,  ..., -0.0051,  0.0711, -0.1054],
         [ 0.3375,  0.0625,  0.2830,  ...,  0.2340,  0.3776, -0.0450],
         [-0.3896,  0.2216,  0.1331,  ...,  0.3938,  0.2011,  0.0772],
         ...,
         [ 0.0120, -0.5948,  0.0944,  ...,  0.1363,  0.1759, -0.1905],
         [-0.4987, -0.2577,  0.1640,  ...,  0.1534,  0.2721, -0.0862],
         [ 0.1297,  0.1059,  0.0162,  ..., -0.0355,  0.1110, -0.1003]]])

In [118]:
logits

tensor([[ 1.2974e-01,  9.2733e-02, -4.3763e-03, -7.6444e-02,  2.1004e-01,
         -1.6128e-02, -9.3786e-03, -1.7504e-01,  1.1201e-01, -1.7964e-01,
          2.9748e-02,  1.4290e-01, -1.0057e-01,  7.4187e-02, -1.9471e-01,
         -1.7847e-01,  1.5923e-01,  8.2522e-02,  1.0709e-01,  3.3974e-01,
          1.1789e-01, -8.2999e-01, -2.1126e-01, -1.3376e-01, -2.2654e-01,
         -2.0141e-02, -3.5608e-02, -1.3771e-01,  5.9053e-02, -1.4969e-01,
          8.3711e-02,  2.2324e-01, -4.5539e-01, -3.2078e-01,  3.9839e-01,
         -4.9884e-02,  2.3450e-02,  8.1071e-03,  3.4386e-01,  1.6797e-01,
          2.6335e-01, -1.6270e-01,  1.3363e-01, -1.7927e-01,  1.3155e-02,
         -6.6555e-02,  2.8972e-01, -1.5185e-01,  2.5111e-01,  2.2836e-01,
          1.1907e-01,  2.1338e-01,  8.7610e-02,  1.1553e-02, -1.8252e-01,
         -5.8658e-01, -2.7819e-01,  4.3526e-01,  5.0713e-01,  1.4345e-01,
         -1.0523e-01, -1.6168e-01,  2.0030e-01,  2.5310e-01,  6.1285e-01,
          7.9898e-02,  2.0140e-01, -1.

In [115]:
y_pred = []
# Afficher les résultats
for i, pred in enumerate(predictions):
    predicted_class = torch.argmax(pred).item()
    if predicted_class == 0:
        y_pred.append(0)
        print(f"Sentence {i + 1}: Sentiment négatif")
    else:
        y_pred.append(1)
        print(f"Sentence {i + 1}: Sentiment positif")

Sentence 1: Sentiment positif
Sentence 2: Sentiment positif
Sentence 3: Sentiment positif
Sentence 4: Sentiment positif
Sentence 5: Sentiment positif
Sentence 6: Sentiment positif
Sentence 7: Sentiment positif
Sentence 8: Sentiment positif
Sentence 9: Sentiment positif
Sentence 10: Sentiment positif
Sentence 11: Sentiment positif
Sentence 12: Sentiment positif
Sentence 13: Sentiment positif
Sentence 14: Sentiment positif
Sentence 15: Sentiment positif
Sentence 16: Sentiment positif
Sentence 17: Sentiment positif
Sentence 18: Sentiment positif
Sentence 19: Sentiment positif
Sentence 20: Sentiment positif
Sentence 21: Sentiment positif
Sentence 22: Sentiment positif
Sentence 23: Sentiment positif
Sentence 24: Sentiment positif
Sentence 25: Sentiment positif
Sentence 26: Sentiment positif
Sentence 27: Sentiment positif
Sentence 28: Sentiment positif
Sentence 29: Sentiment positif
Sentence 30: Sentiment positif
Sentence 31: Sentiment positif
Sentence 32: Sentiment positif
Sentence 33: Sent

In [79]:
import torch
from transformers import AutoModel, AutoTokenizer 

bertweet = AutoModel.from_pretrained("vinai/bertweet-large")

tokenizer = AutoTokenizer.from_pretrained("vinai/bertweet-large")

# INPUT TWEET IS ALREADY NORMALIZED!
line = "DHEC confirms HTTPURL via @USER :crying_face:"

input_ids = torch.tensor([tokenizer.encode(line)])

with torch.no_grad():
    features = bertweet(input_ids)  # Models outputs are now tuples
    
## With TensorFlow 2.0+:
# from transformers import TFAutoModel
# bertweet = TFAutoModel.from_pretrained("vinai/bertweet-large")

Some weights of RobertaModel were not initialized from the model checkpoint at vinai/bertweet-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
vocab.json: 100%|██████████| 899k/899k [00:00<00:00, 14.4MB/s]
merges.txt: 100%|██████████| 456k/456k [00:00<00:00, 1.83MB/s]
tokenizer.json: 100%|██████████| 1.36M/1.36M [00:00<00:00, 5.36MB/s]


In [83]:
features[0]

tensor([[[ 0.0862,  0.0521, -0.1026,  ...,  0.0147,  0.1891, -0.0736],
         [ 0.1007, -0.0159, -0.6580,  ...,  0.1054,  0.2050,  0.0699],
         [ 0.2216,  0.0395, -0.5482,  ..., -0.1893,  0.3768,  0.2154],
         ...,
         [ 0.0523,  0.2308, -0.8912,  ...,  0.3122, -0.0351, -0.0617],
         [-0.0252, -0.1803, -0.0527,  ...,  0.3899, -0.1398, -0.2169],
         [ 0.0499,  0.0034, -0.1559,  ..., -0.0495,  0.1139, -0.0543]]])

In [72]:
# Vos données tokenisées
tabX = []
for sentence in df_sample['words']:
    testX = torch.tensor([tokenizer.encode(sentence)])
    tabX.append(testX)

# Vos embeddings
tabY = []
for i in tabX:
    with torch.no_grad():
        features = bertweet(i)
    tabY.append(features.logits)

# Concaténer les embeddings
features_tensor = torch.cat(tabY, dim=0)

# Calculer les prédictions
predictions = torch.nn.Softmax(dim=-1)(features_tensor)

AttributeError: 'BaseModelOutputWithPoolingAndCrossAttentions' object has no attribute 'logits'

In [62]:
from transformers import BertForSequenceClassification, BertTokenizer

# Charger le modèle BERT pour la classification de séquences
bert_model = BertForSequenceClassification.from_pretrained("bert-base-uncased", num_labels=2)  # 2 classes : positif et négatif
tokenizer = BertTokenizer.from_pretrained("bert-base-uncased")

# Vos données tokenisées
tabX = []
for sentence in df_sample['words']:
    testX = torch.tensor([tokenizer.encode(sentence)])
    tabX.append(testX)

# Vos embeddings
tabY = []
for i in tabX:
    with torch.no_grad():
        features = bert_model(i)
    tabY.append(features.logits)

# Concaténer les embeddings
features_tensor = torch.cat(tabY, dim=0)

# Calculer les prédictions
predictions = torch.nn.Softmax(dim=-1)(features_tensor)

y_pred = []
# Afficher les résultats
for i, pred in enumerate(predictions):
    predicted_class = torch.argmax(pred).item()
    if predicted_class == 0:
        y_pred.append(0)
        print(f"Sentence {i + 1}: Sentiment négatif")
    else:
        y_pred.append(1)
        print(f"Sentence {i + 1}: Sentiment positif")


Some weights of BertForSequenceClassification were not initialized from the model checkpoint at bert-base-uncased and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.


Sentence 1: Sentiment négatif
Sentence 2: Sentiment positif
Sentence 3: Sentiment positif
Sentence 4: Sentiment négatif
Sentence 5: Sentiment positif
Sentence 6: Sentiment positif
Sentence 7: Sentiment positif
Sentence 8: Sentiment négatif
Sentence 9: Sentiment négatif
Sentence 10: Sentiment positif
Sentence 11: Sentiment négatif
Sentence 12: Sentiment positif
Sentence 13: Sentiment négatif
Sentence 14: Sentiment positif
Sentence 15: Sentiment négatif
Sentence 16: Sentiment négatif
Sentence 17: Sentiment négatif
Sentence 18: Sentiment négatif
Sentence 19: Sentiment négatif
Sentence 20: Sentiment négatif
Sentence 21: Sentiment positif
Sentence 22: Sentiment négatif
Sentence 23: Sentiment positif
Sentence 24: Sentiment négatif
Sentence 25: Sentiment positif
Sentence 26: Sentiment négatif
Sentence 27: Sentiment négatif
Sentence 28: Sentiment positif
Sentence 29: Sentiment négatif
Sentence 30: Sentiment positif
Sentence 31: Sentiment négatif
Sentence 32: Sentiment positif
Sentence 33: Sent

In [64]:
from sklearn.metrics import accuracy_score

accuracy = accuracy_score(df_sample['target'], y_pred)
print("Accuracy:", accuracy)

Accuracy: 0.464


In [66]:
df_sample

target          id                          date      flag  \
106921       1  2176348551  Mon Jun 15 03:37:41 PDT 2009  NO_QUERY   
393637       1  1680920265  Sat May 02 12:48:07 PDT 2009  NO_QUERY   
97927        1  2179515363  Mon Jun 15 09:12:33 PDT 2009  NO_QUERY   
539346       0  1967832797  Fri May 29 20:17:28 PDT 2009  NO_QUERY   
273561       1  2191950841  Tue Jun 16 06:15:21 PDT 2009  NO_QUERY   
...        ...         ...                           ...       ...   
927021       1  2187413080  Mon Jun 15 20:14:42 PDT 2009  NO_QUERY   
685351       1  1980042753  Sun May 31 05:29:00 PDT 2009  NO_QUERY   
340960       1  2191983906  Tue Jun 16 06:18:43 PDT 2009  NO_QUERY   
513538       1  1979140426  Sun May 31 01:48:07 PDT 2009  NO_QUERY   
257400       1  2187044995  Mon Jun 15 19:42:34 PDT 2009  NO_QUERY   

                 user                                               text  \
106921   Knusperkeks5              hilfe anna anne is very crazy person    
393637  josephranseth  sure thing should we start with ustream amp bl...   
97927       cbeard765      save it some day it will be valuable antique    
539346      Natashahh   try calling so many times didnt get thew it w...   
273561        gail666                forget the village ill ask my brov    
...               ...                                                ...   
927021      brittslay  just wants the whole world to know that is the...   
685351      Plookster  the tea is for washing down the scones cakes c...   
340960      siana_mia                         that is very sweet thanks    
513538  honeydewjuice   miss you really really miss you way to call m...   
257400   Miss_Darling  night all time to snuggle up with everyone in ...   

                                                    words  
106921                       hilfe anna anne crazy person  
393637  sure thing start ustream amp blip channel go b...  
97927                           save day valuable antique  
539346  try call many time didnt get thew would really...  
273561                        forget village ill ask brov  
...                                                   ...  
927021                 want whole world know bestest ever  
685351  tea wash scone cake cooky sandwich anything el...  
340960                                       sweet thanks  
513538  miss really really miss way call back whatever...  
257400     night time snuggle everyone full king size bed  

[1000 rows x 7 columns]

In [43]:
text = 'I am so happy to see you at this evening!'
input_ids = torch.tensor([tokenizer.encode(text)])
input_ids


tensor([[    0,     8,   155,    39,   225,     9,    95,    14,    35,    33,
         11613,   856,    12,     2]])

In [ ]:
with torch.no_grad():
    features = bertweet(input_ids)

In [12]:
classification_model = torch.nn.Sequential(
    torch.nn.Linear(features.last_hidden_state.shape[-1], 2),  # 2 classes : positif et négatif
    torch.nn.Softmax(dim=-1)
)

# Calculer les prédictions
predictions = classification_model(features.last_hidden_state[:, 0, :])

# Afficher le résultat
predicted_class = torch.argmax(predictions).item()
if predicted_class == 0:
    print("Sentiment négatif")
else:
    print("Sentiment positif")

Sentiment positif
